MichaelChirico/potools

R/build_gettextf_call.R, tests/testthat/helpers.R, tests/testthat/test-translate-package.R, tests/testthat/test_packages/no_msg/DESCRIPTION, tests/testthat/test_packages/no_msg/R/foo.R
=> add first test package & first mock run-through without error

R/onLoad.R, R/translate_package.R, R/utils.R, tests/testthat/mock_translations/test-translate-package-r_msg-1.input, tests/testthat/test-translate-package.R, tests/testthat/test_packages/r_msg/DESCRIPTION, tests/testthat/test_packages/r_msg/R/foo.R
=> re-tool prompt() internals to work as intended in tests

R/get_po_messages.R, R/get_r_messages.R, R/translate_package.R, R/utils.R, R/write_po_file.R, tests/testthat/test-translate-package.R
=> add first tracing

R/translate_package.R, R/utils.R, tests/testthat/helpers.R, tests/testthat/mock_translations/test-translate-package-r_msg-1.input, tests/testthat/test-translate-package.R, tests/testthat/test_packages/r_msg/R/foo.R
=> add tests for a plural message  & more

R/translate_package.R, R/utils.R, tests/testthat/test-translate-package.R
=> test re-translation

R/utils.R, tests/testthat/test-translate-package.R
=> test most of R/utils.R

tests/testthat/helpers.R, tests/testthat/mock_translations/test-translate-package-r_msg-1.input, tests/testthat/test-translate-package.R, tests/testthat/test_packages/r_msg/R/foo.R
=> Test templated

R/get_po_messages.R, R/get_r_messages.R, tests/testthat/mock_translations/test-translate-package-r_msg-1.input, tests/testthat/test_packages/r_msg/R/foo.R, tests/testthat/test_packages/r_msg/R/windows/bar.R
Closes #6
This will be it for #6 for now. Some more coverage can be had, but certainly sufficient to proceed with features for the package.
=> add more to r_msg package for coverage

R/get_r_messages.R, R/utils.R, tests/testthat/test_packages/r_msg/R/foo.R
Akin to base patch: https://bugs.r-project.org/bugzilla/show_bug.cgi?id=18025
=> extend get_r_messages to work for namespace-qualified calls

README.md, man/translate_package.Rd
cc @llrs -- PTAL and let me know if that helps clarify things
=> add some notes on picking a domain

R/build_gettextf_call.R, R/check_cracked_messages.R, tests/testthat/test-translate-package.R, tests/testthat/test_packages/r_non_template/R/foo.R
=> improve check_cracked_messages logic

R/check_untranslated_cat.R, tests/testthat/test-translate-package.R, tests/testthat/test_packages/r_cat_msg/R/foo.R
=> encodeString() in check_untranslated_cat output

R/check_cracked_messages.R, R/check_untranslated_cat.R, R/check_untranslated_src.R, R/get_r_messages.R, R/translate_package.R, tests/testthat/test-translate-package.R, tests/testthat/test_packages/plural_semi_named/DESCRIPTION, tests/testthat/test_packages/plural_semi_named/R/foo.R, tests/testthat/test_packages/r_cat_msg/R/foo.R, tests/testthat/test_packages/r_fuzzy/R/foo.R, tests/testthat/test_packages/r_msg/R/foo.R
Closes #70; helps facilitate #66, #30, #25
=> check_untranslated_cat uses get_r_messages data table

R/check_untranslated_cat.R, tests/testthat/test_packages/r_cat_msg/R/foo.R, tests/testthat/test_packages/r_non_template/R/foo.R, tests/testthat/test_packages/r_src_c/R/foo.R
=> Refine check_untranslated_cat to ignore partially-translated calls

NAMESPACE, R/build_gettextf_call.R, R/check_cracked_messages.R, R/check_untranslated_cat.R, R/check_untranslated_src.R, R/onLoad.R, R/show_diagnostic_results.R, R/translate_package.R, man/check_cracked_messages.Rd, man/check_untranslated_cat.Rd, man/check_untranslated_src.Rd, man/translate_package.Rd, tests/testthat/test-diagnostics.R
=> Expose diagnostics as an option (and export existing diagnostics)

R/translate_package.R, R/write_po_file.R, man/translate_package.Rd, tests/testthat/test-translate-package.R, tests/testthat/test_packages/unusual_msg/src/msg.c
=> New use_base_rules argument to hew to base behavior

R/write_po_file.R, tests/testthat/test-translate-package.R
=> fix exclusion of c-format from src po/pot

R/get_r_messages.R, tests/testthat/mock_translations/test-translate-package-unusual_msg-1.input, tests/testthat/test-translate-package.R, tests/testthat/test_packages/r_fuzzy/R/foo.R, tests/testthat/test_packages/r_msg/R/windows/bar.R, tests/testthat/test_packages/unusual_msg/R/foo.R, tests/testthat/test_packages/unusual_msg/R/windows/bar.R, tests/testthat/test_packages/unusual_msg/src/msg.c
=> Adjust whitespace trimming to match base behavior

R/write_po_file.R, tests/testthat/test-translate-package.R
=> src markers are wrapped to match base behavior

R/write_po_file.R, tests/testthat/mock_translations/test-translate-package-unusual_msg-1.input, tests/testthat/test-translate-package.R, tests/testthat/test_packages/unusual_msg/src/msg.c
=> ' gets bumped to the next line along with templates when wrapping in write_po_files

tests/testthat/test-translate-package.R
=> add some tests for the diagnostic=

R/get_src_messages.R, R/translate_package.R, R/utils.R, tests/testthat/mock_translations/test-translate-package-unusual_msg-2.input, tests/testthat/test-translate-package.R, tests/testthat/test_packages/unusual_msg/src/strange/bedfellows.c
=> exclude files not in src or src/windows when use_base_rules=TRUE

NAMESPACE, R/onLoad.R, R/translate_package.R, man/translate_package.Rd, tests/testthat/test-translate-package.R, tests/testthat/test_packages/grDevices/DESCRIPTION, tests/testthat/test_packages/grDevices/NAMESPACE, tests/testthat/test_packages/grDevices/R/mask.R, tests/testthat/test_packages/grDevices/src/cairo/cairoBM.c, tests/testthat/test_packages/grDevices/src/cairo/cairoBM.h, tests/testthat/test_packages/grDevices/src/grDevices.h, tests/testthat/test_packages/grDevices/src/mask.c
=> auto-detect if use_base_rules needs to be set

R/write_po_file.R, tests/testthat/test-translate-package.R, tests/testthat/test_packages/grDevices/R/colorRamp.R, tests/testthat/test_packages/grDevices/R/mask.R
=> use package=R for base packages

R/write_po_file.R, tests/testthat/test-translate-package.R
=> auto-set bugs for base

R/write_po_file.R, tests/testthat/test-translate-package.R, tests/testthat/test_packages/grDevices/src/qdPDF.c
=> handle copyright disrepancy for base src .pot files

R/get_r_messages.R, tests/testthat/mock_translations/test-translate-package-unusual_msg-1.input, tests/testthat/mock_translations/test-translate-package-unusual_msg-2.input, tests/testthat/test-translate-package.R, tests/testthat/test_packages/unusual_msg/R/foo.R
=> fix quote escaping in R

R/get_r_messages.R, tests/testthat/test-translate-package.R, tests/testthat/test_packages/unusual_msg/R/foo.R
=> Correctly handle consecutive escapes

R/read_translation.R, R/utils.R, tests/testthat/mock_translations/test-translate-package-unusual_msg-1.input, tests/testthat/mock_translations/test-translate-package-unusual_msg-2.input, tests/testthat/test-translate-package.R, tests/testthat/test_packages/unusual_msg/src/msg.c
=> extend c-format regex to recognize more formatters

R/get_src_messages.R, tests/testthat/test_packages/unusual_msg/src/msg.c
=> fix incorrect jump around escaped char

R/utils.R, tests/testthat/mock_translations/test-translate-package-unusual_msg-1.input, tests/testthat/mock_translations/test-translate-package-unusual_msg-2.input, tests/testthat/test_packages/unusual_msg/src/msg.c
=> also recognize %ls as a formatter

R/get_r_messages.R, R/get_src_messages.R, tests/testthat/mock_translations/test-translate-package-unusual_msg-1.input, tests/testthat/test-translate-package.R
=> set order of files in .pot to match base

R/get_src_messages.R, tests/testthat/mock_translations/test-translate-package-unusual_msg-1.input, tests/testthat/mock_translations/test-translate-package-unusual_msg-2.input, tests/testthat/test-translate-package.R, tests/testthat/test_packages/unusual_msg/src/msg.c
=> add line numbers for msgid found outside an "outer" call

R/write_po_file.R, tests/testthat/mock_translations/test-translate-package-unusual_msg-1.input, tests/testthat/mock_translations/test-translate-package-unusual_msg-2.input, tests/testthat/test-translate-package.R, tests/testthat/test_packages/unusual_msg/src/ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz01234567890.c, tests/testthat/test_packages/unusual_msg/src/msg.c
=> get strwrap behavior for file markers exactly right

R/get_src_messages.R, tests/testthat/test-translate-package.R, tests/testthat/test_packages/unusual_msg/src/cairo/bedfellows.c
=> fix incorrect src line number when call & array lines differ

R/get_src_messages.R, R/onLoad.R, R/translate_package.R, man/translate_package.Rd, tests/testthat/mock_translations/test-translate-package-r_src_c-1.input, tests/testthat/test-translate-package.R, tests/testthat/test_packages/r_src_c/src/bar.c
=> extend get_src_messages to understand N_-marked translations

R/get_r_messages.R, R/get_src_messages.R, R/utils.R, R/write_po_file.R, tests/testthat/mock_translations/test-translate-package-r_src_c-1.input, tests/testthat/mock_translations/test-translate-package-unusual_msg-1.input, tests/testthat/mock_translations/test-translate-package-unusual_msg-2.input, tests/testthat/test-translate-package.R, tests/testthat/test_packages/r_src_c/src/bar.c, tests/testthat/test_packages/unusual_msg/src/msg.c
=> snprintf() calls are marked as templated regardless of actual templates

R/get_src_messages.R, tests/testthat/mock_translations/test-translate-package-r_src_c-1.input, tests/testthat/test-diagnostics.R, tests/testthat/test-translate-package.R, tests/testthat/test_packages/r_src_c/src/bar.c
=> Support for plural messages in src

R/get_r_messages.R, R/get_src_messages.R, R/translate_package.R, R/utils.R, tests/testthat/test-translate-package.R, tests/testthat/test_packages/r-devel/share/R/shared.R
=> Include files from share/R to R-base.pot

R/get_po_messages.R
Closes #98
The issue was that we assumed `msgid "` when it's actually `msgid +"` is valid.
However I'm not sure how to test this (notably, the issue was already affecting the `.pot` file in `r_fuzzy`)...
=> fix .po/.pot reading issue

NAMESPACE, R/get_r_messages.R, tests/testthat/mock_translations/test-translate-package-unusual_msg-1.input, tests/testthat/test-translate-package.R, tests/testthat/test_packages/unusual_msg/R/foo.R
=> Retrieve nested strings from gettextf

NAMESPACE, R/add_new_metadata.R, R/check_cracked_messages.R, R/check_untranslated_src.R, R/custom-translators.R, R/find_fuzzy_messages.R, R/get_message_data.R, R/get_po_messages.R, R/get_r_messages.R, R/get_src_messages.R, R/msgmerge.R, R/read_translation.R, R/show_diagnostic_results.R, R/specials_metadata.R, R/translate_package.R, R/utils.R, man/check_untranslated_src.Rd, man/get_message_data.Rd, man/translate_package.Rd, tests/testthat/test-get-message-data.R, tests/testthat/test_packages/custom_translation/DESCRIPTION, tests/testthat/test_packages/custom_translation/R/custom1.R, tests/testthat/test_packages/custom_translation/R/custom2.R, tests/testthat/test_packages/custom_translation/src/custom1.c
=> Support custom translation interfaces in R & src

R/custom-translators.R, R/get_r_messages.R, R/get_src_messages.R
moving into a PR so as not to pollute master too much
=> fix attempts for windows

R/get_src_messages.R, man/translate_package.Rd, tests/testthat/mock_translations/test-translate-package-unusual_msg-1.input, tests/testthat/test-translate-package.R, tests/testthat/test_packages/r-devel/src/library/grDevices/src/mask.c, tests/testthat/test_packages/unusual_msg/src/msg.c
=> properly ignore first arg to dgettext

NEWS.md, R/translate_package.R, man/translate_package.Rd, tests/testthat/test-translate-package.R
=> New max_translations argument for translate_package

tests/testthat/test-translate-package.R
=> tighten test for en@quot messages

NAMESPACE, NEWS.md, R/add_new_metadata.R, R/onLoad.R, R/read_translation.R, R/translate_package.R, tests/testthat/helpers.R, tests/testthat/mock_translations/test-translate-package-r_msg-2.input, tests/testthat/mock_translations/test-translate-package-r_msg-5.input, tests/testthat/test-translate-package.R
=> flexibility for whitespace in add_new_metadata

NAMESPACE, NEWS.md, R/get_r_messages.R, R/get_src_messages.R, R/onLoad.R, R/utils.R, tests/testthat/test-get-message-data.R, tests/testthat/test_packages/r_err_1/DESCRIPTION, tests/testthat/test_packages/r_err_1/NAMESPACE, tests/testthat/test_packages/r_err_1/R/foo.R, tests/testthat/test_packages/r_err_2/DESCRIPTION, tests/testthat/test_packages/r_err_2/NAMESPACE, tests/testthat/test_packages/r_err_2/R/foo.R, tests/testthat/test_packages/r_msg/R/foo.R, tests/testthat/test_packages/r_src_c/src/bar.c
Closes #10.
I still think the same being done for src may in reach; to be tested.
=> support excluding regions with #notranslate

NAMESPACE, NEWS.md, R/onLoad.R, R/translate_package.R, R/update_metadata.R, R/utils.R, R/write_po_file.R, man/get_message_data.Rd, man/translate_package.Rd, man/write_po_file.Rd, tests/testthat/test-translate-package.R, tests/testthat/test-write-po-file.R
Closes #168; Closes #76 as well
=> Export write_po_file

man/translate_package.Rd
=> more explicit about the custom translation of ... functions

README.md
Related: #202. Not closing since I think a vignette would still have value, but tabling for this release.
=> add some example translate_package() usage to the README

R/write_po_file.R, tests/testthat/test-write-po-file.R
=> fix charset=UTF-8 in template, add test

R/utils.R, R/write_po_file.R, tests/testthat/test-write-po-file.R, tests/testthat/test_packages/r-devel/src/main/msg.c
=> fix plural entries in .pot when use_base_rules=TRUE

R/write_po_file.R, tests/testthat/test-write-po-file.R
=> fine-tuning .pot output

R/write_po_file.R, tests/testthat/test-write-po-file.R
=> use %z to format timestamps in .po/.pot

NEWS.md, R/msgmerge.R, R/write_po_file.R, tests/testthat/test-translate-package.R, tests/testthat/test-write-po-file.R
=> Solaris msgfmt

DESCRIPTION, NEWS.md, R/get_message_data.R, R/translate_package.R, R/utils.R, man/get_message_data.Rd, man/translate_package.Rd, tests/testthat/test-diagnostics.R, tests/testthat/test-get-message-data.R
=> testthat --> 3rd edition

R/specials_metadata.R, tests/testthat/mock_translations/test-translate-package-r_msg-2.input, tests/testthat/test-translate-package.R
=> refine error message around bordering newlines

man/po_compile.Rd, man/po_extract.Rd
I think I forgot to turn markdown mode on in one of the PRs
=> Re-document

DESCRIPTION
Hope you don't mind the use of `use_tidy_description()`; I think it's worthwhile to put each dependency on its own line to slightly simplify merges.
=> Description updates

R/po_update.R, man/po_update.Rd, man/potools-package.Rd
=> use an ASCII language to demonstrate translations

DESCRIPTION, man/potools-package.Rd
=> Fix Authors@R syntax

README.md
at the moment this part appears like a code block.
=> fix markup

NEWS.md, R/msgmerge.R, R/onLoad.R, R/utils.R, man/check_potools_sys_reqs.Rd
Closes #275 
Something like this you had in mind @hadley? I'm wondering if the "cache"ing is overkill...
=> Check system requirements whenever run_* functions are run

vignettes/developers.Rmd
=> add a paragraph about the importance of message reordering

NEWS.md, R/msgmerge.R, R/utils.R
=> improve test for gnu gettext

inst/extdata/language_metadata.csv
=> fix label of dutch, add norwegian

.github/workflows/R-CMD-check.yaml, .github/workflows/pkgdown.yaml, .github/workflows/test-coverage.yaml, vignettes/custom-diagnostic.Rmd
I noticed this vignette has no TOC in the pkgdown website :-)
=> Change header levels in custom-diagnostic vignette

.github/workflows/lint.yaml
Copied from https://github.com/r-lib/lintr/blob/4a8b9316e0349804a87eff3cb25152d196535265/.github/workflows/lint.yaml
=> lint workflow

README.md
- Explain the difference between both
- Change thesis URL to uni repo
- Add mention to Weblate and its usage in R
- Close issue #308
=> differentiate Pootle from Virtaal
